// Copyright 2024 IOTA Stiftung.
// SPDX-License-Identifier: Apache-2.0.

export { default as ArrowRight } from "./arrowRight";
export { default as ArrowRightFat } from "./arrowRightFat";
export { default as Bag } from "./bag";
export { default as Bell } from "./bell";
export { default as Briefcase } from "./briefcase";
export { default as Building } from "./building";
export { default as CalendarDots } from "./calendarDots";
export { default as Camera } from "./camera";
export { default as CaretDown } from "./caretDown";
export { default as CaretLeft } from "./caretLeft";
export { default as ChartBar } from "./chartBar";
export { default as Check } from "./check";
export { default as CheckCircle } from "./checkCircle";
export { default as Clipboard } from "./clipboard";
export { default as Clock } from "./clock";
export { default as DotsThreeVertical } from "./dotsThreeVertical";
export { default as Envelope } from "./envelope";
export { default as Eye } from "./eye";
export { default as File } from "./file";
export { default as FileLock } from "./fileLock";
export { default as FilePdf } from "./filePdf";
export { default as Fingerprint } from "./fingerprint";
export { default as Fire } from "./fire";
export { default as Folders } from "./folders";
export { default as Gear } from "./gear";
export { default as Globe } from "./globe";
export { default as House } from "./house";
export { default as IdentificationCard } from "./identificationCard";
export { default as Image } from "./image";
export { default as Info } from "./info";
export { default as Keyboard } from "./keyboard";
export { default as Link } from "./link";
export { default as List } from "./list";
export { default as Lock } from "./lock";
export { default as MagnifyingGlass } from "./magnifyingGlass";
export { default as MapPin } from "./mapPin";
export { default as Megaphone } from "./megaphone";
export { default as PencilLine } from "./pencilLine";
export { default as Phone } from "./phone";
export { default as PlayStop } from "./playStop";
export { default as Plus } from "./plus";
export { default as Question } from "./question";
export { default as SealCheck } from "./sealCheck";
export { default as SealPercent } from "./sealPercent";
export { default as ShieldWarning } from "./shieldWarning";
export { default as ShoppingCart } from "./shoppingCart";
export { default as Star } from "./star";
export { default as Trash } from "./trash";
export { default as Upload } from "./upload";
export { default as UserCircle } from "./userCircle";
export { default as UserPlus } from "./userPlus";
export { default as UserRectangle } from "./userRectangle";
export { default as UsersThree } from "./usersThree";
export { default as WarningCircle } from "./warningCircle";
export { default as X } from "./x";

// Export the props type
export type { IconsProps } from "../types/iconTypes";
